Repository lambdaclass/champions_of_mirra, pull requests merged in 2024-06, with the labels that each got.

#1798 [GH-1617] connectivity issues feedback
  client/Assets/Images/UI/BattleUI/InGameUI/Connectivity.meta
  client/Assets/Images/UI/BattleUI/InGameUI/Connectivity/connection error.png
  client/Assets/Images/UI/BattleUI/InGameUI/Connectivity/connection error.png.meta
  client/Assets/Prefabs/Camera/CameraUI.prefab
  client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
  client/Assets/Prefabs/Managers/LevelManager.prefab
  client/Assets/Scenes/Battle.unity
  client/Assets/Scripts/ConnectionHealthAnalyzer.cs
  client/Assets/Scripts/ConnectionHealthAnalyzer.cs.meta
  client/Assets/Scripts/ConnectionStateIcon.cs
  client/Assets/Scripts/ConnectionStateIcon.cs.meta
  client/Assets/Scripts/GameServerConnectionManager.cs
  client/Assets/Scripts/Messages.pb.cs
  client/Assets/Scripts/PingCounter.cs
  messages.proto
Labels: waiting on

#1814 Fix dynamic font assets changing version control
  client/Assets/Resources/Fonts/SourceSans3-Bold SDF.asset
  client/Assets/Resources/Fonts/SourceSans3-ExtraBold SDF.asset
  client/Assets/Resources/Fonts/SourceSans3-Light SDF.asset
  client/Assets/Resources/Fonts/SourceSans3-Medium SDF.asset
  client/Assets/Resources/Fonts/SourceSans3-MediumItalic SDF.asset
  client/Assets/Scripts/DynamicFontAssetAutoClear.cs
  client/Assets/Scripts/DynamicFontAssetAutoClear.cs.meta
Labels: bug, unity, improvement

#1803 Authentication with JWT
  client/Assets/Scenes/TitleScreen.unity
  client/Assets/Scripts/GameServerConnectionManager.cs
  client/Assets/Scripts/GoogleSignIn/GoogleSignInController.cs
  client/Assets/Scripts/GuestSignIn.meta
  client/Assets/Scripts/GuestSignIn/GuestSignInController.cs
  client/Assets/Scripts/GuestSignIn/GuestSignInController.cs.meta
  client/Assets/Scripts/ServerConnection.cs
  client/Assets/Scripts/Utils/ServerUtils.cs
Labels: waiting on

#1840 [GH-1831] Add toggle bots button
  client/Assets/Prefabs/UI/BattleSettingsSplash.prefab
  client/Assets/Scenes/Battle.unity
  client/Assets/Scripts/Battle.cs
  client/Assets/Scripts/GameServerConnectionManager.cs
  client/Assets/Scripts/Messages.pb.cs
  client/Assets/Scripts/UI/Settings/BattleSettingsController.cs
  messages.proto
Labels: waiting on

#1856 Improved performance on damage feedback
  client/Assets/Materials/Characters/H4ck/Shader Graphs_S_CheracterGeneric_H4ck.mat
  client/Assets/Materials/Characters/Muflus/Shader Graphs_S_CheracterGeneric_Muflus.mat
  client/Assets/Materials/Characters/Uma/Shader Graphs_S_CheracterGeneric_Uma.mat
  client/Assets/Materials/Characters/Valtimer/Shader Graphs_S_CheracterGeneric_Valtimer.mat
  client/Assets/Prefabs/Characters/H4ck.prefab
  client/Assets/Prefabs/Characters/Muflus.prefab
  client/Assets/Prefabs/Characters/Uma.prefab
  client/Assets/Prefabs/Characters/Valtimer.prefab
  client/Assets/Prefabs/VisualEffects/H4ck_Denial_AOE.prefab
  client/Assets/Scripts/CharacterFeedbackManager.cs
  client/Assets/Scripts/CharacterFeedbacks.cs
  client/Assets/Scripts/CustomCharacter.cs
  client/Assets/Shaders/S_CheracterGeneric.shadergraph
Labels: high priority
