Repository lambdaclass/champions_of_mirra, pull requests merged in 2024-07, with the labels that each got.

#1882 Implement crate dropping delay and power up activation delay
  client/Assets/Scripts/Messages.pb.cs
  client/Assets/Scripts/PowerUpsManager.cs
  messages.proto
Labels: waiting on

#1873 Fix game timers
  client/Assets/Scripts/GameServerConnectionManager.cs
Labels: waiting on

#1909 Add missing reference for uma's giantVFX
  client/Assets/Prefabs/Characters/Uma.prefab
Labels: high priority

#1908 Minor UI modifications
  client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
  client/Assets/Scenes/TitleScreen.unity
Labels: high priority

#1914 Update power ups
  client/Assets/Prefabs/Managers/BattleManager.prefab
  client/Assets/Scenes/VFX_Items_test_scene.unity
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_BaseMap.png
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_BaseMap.png.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_Emissive.png
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_Emissive.png.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_MaskMap.png
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_MaskMap.png.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_Normal.png
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_Normal.png.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_Opacity.png
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/Low_Power_Up_Opacity.png.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/M_PowerUp_0.mat
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/M_PowerUp_0.mat.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpItem.prefab
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpItem.prefab.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Mesh.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Mesh/SM_Lighting.fbx
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Mesh/SM_Lighting.fbx.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/PowerUp.prefab
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/PowerUp.prefab.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Shaders.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Shaders/S_Arow&Sphere.shadergraph
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Shaders/S_Arow&Sphere.shadergraph.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Shaders/S_LightingParticles.shadergraph
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Shaders/S_LightingParticles.shadergraph.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Textures.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Textures/T_CircleGlow.tga
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Textures/T_CircleGlow.tga.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Textures/T_Flare1.tga
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Textures/T_Flare1.tga.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Textures/T_Lighting 1.tga
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/Textures/T_Lighting 1.tga.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/VFXPowerUp.vfx
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/PowerUpVFX/VFXPowerUp.vfx.meta
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/SM_PowerUp_Low.fbx
  client/Assets/VFX-Tools/PIngle_VFX/PowerUp/SM_PowerUp_Low.fbx.meta
  client/Assets/VFX-Tools/Pingle_Tools/ItemLevitatingController.cs
  client/Assets/VFX-Tools/Pingle_Tools/ItemLevitatingController.cs.meta
Labels: high priority

#1910 Fix effects handling
  client/Assets/Scripts/CharacterFeedbackManager.cs
  client/Assets/Scripts/Effects/CharacterMaterialManager.cs
  client/Assets/Scripts/Effects/EffectCharacterMaterialController.cs
  client/Assets/Scripts/Effects/MaterialSettingsBlock.cs
Labels: high priority

#1927 Add two new spikes
  client/Assets/Images/Spikes/Scale 4.png
  client/Assets/Images/Spikes/Scale 4.png.meta
  client/Assets/Materials/Obstacles/SpikesIndicator_small.mat
  client/Assets/Materials/Obstacles/SpikesIndicator_small.mat.meta
  client/Assets/Prefabs/Maps/Colliders.prefab
  client/Assets/Prefabs/Spikes/Spikes.prefab
  client/Assets/Scenes/Battle.unity
Labels: waiting on

#1877 Add missing bounty information
  client/Assets/Images/UI/BattleUI/EndGame/Bounties/completed icon.png
  client/Assets/Images/UI/Buttons/claim-bounty-button-disable.png
  client/Assets/Images/UI/Buttons/claim-bounty-button-disable.png.meta
  client/Assets/Images/UI/Buttons/claim-bounty-button.png
  client/Assets/Images/UI/Buttons/claim-bounty-button.png.meta
  client/Assets/Images/UI/Buttons/quick-game-button.png
  client/Assets/Images/UI/Buttons/quick-game-button.png.meta
  client/Assets/Images/UI/Main/currency container.png
  client/Assets/Images/UI/Main/currency container.png.meta
  client/Assets/Prefabs/Camera/BattleCameraUI.prefab
  client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
  client/Assets/Prefabs/UI/Bounty.prefab
  client/Assets/Prefabs/UI/BountyCompletedPopUp.prefab
  client/Assets/Prefabs/UI/BountyCompletedPopUp.prefab.meta
  client/Assets/Prefabs/UI/DeathSplash.prefab
  client/Assets/Scenes/Battle.unity
  client/Assets/Scenes/MainScreen.unity
  client/Assets/Scripts/Battle.cs
  client/Assets/Scripts/GoogleSignIn/GoogleSignInController.cs
  client/Assets/Scripts/GuestSignIn/GuestSignInController.cs
  client/Assets/Scripts/Messages.pb.cs
  client/Assets/Scripts/UI/Bounty.cs
  client/Assets/Scripts/UI/BountyCompletionManager.cs
  client/Assets/Scripts/UI/BountyCompletionManager.cs.meta
  client/Assets/Scripts/UI/EndGame/EndGameManager.cs
  client/Assets/Scripts/UI/MainScreenManager.cs
  client/Assets/Scripts/Utils/ServerUtils.cs
  messages.proto
Labels: high priority, waiting on
